source: astro-microblog
output: dist

editor:
  default_item_editor: visual

collections_config:
  pages:
    path: src/pages
    output: true
    name: ページ編集
    # ここが重要！.astroファイルからデータを抜き出す設定です
    parser: front-matter
    config:
      allowed_views: [visual, data]
  blog:
    path: src/content/blog
    output: true
    name: ブログ記事