# astro-microblog/cloudcannon.config.yml の内容
source: astro-microblog
output: astro-microblog/dist

# 編集画面の設定
editor:
  default_item_editor: visual

# サイドメニュー（コレクション）の定義
collections_config:
  pages:
    path: src/pages
    output: true
    name: ページ編集
    config:
      allowed_views: [visual, data]
  blog:
    path: src/content/blog
    output: true
    name: ブログ記事